# https://github.com/gruntwork-io/terragrunt-action
#https://github.com/autero1/action-terragrunt
# https://dev.to/aws-builders/provision-eks-cluster-with-terraform-terragrunt-github-actions-1c64
name: 'Terragrunt GitHub Actions'
permissions:
  id-token: write
  pull-requests: write
on:
  push:
    branches:
      - stage_branch
  pull_request:
    branches:
      - stage_branch

env:
  tf_version: '1.11.3'
  tg_version: '0.67.0'
  working_dir: './environments/dev'
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  validate_plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-skip-session-tagging: true
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::719798204634:role/GitHub-role-test
      - name: Create Terraform Plugin Cache Dir
        run: mkdir -p $TF_PLUGIN_CACHE_DIR
      
      - name: Terraform Plugin Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Validate
        uses: gruntwork-io/terragrunt-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_PLUGIN_CACHE_DIR: /github/workspace/.terraform.d/plugin-cache
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'validate'
          tg_comment: 1

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_PLUGIN_CACHE_DIR: /github/workspace/.terraform.d/plugin-cache
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
          tg_comment: 1
      - name: List files
        run: tree

  deploy:
    runs-on: ubuntu-latest
    needs: [ validate_plan ]
    #environment: 'prod'
    #if: github.event.pull_request.base.ref == 'stage_branch'
    if: github.event_name == 'push'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-skip-session-tagging: true
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::719798204634:role/GitHub-role-test

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'apply'